<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="RAM-PC" name="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner" tests="4" failures="1" timestamp="12 Mar 2020 09:02:58 GMT" time="0.051" errors="0">
  <testcase name="Test2" time="0.011" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test1" time="0.036" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner"/>
  <testcase name="Test2" time="0.002" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner.Test2(TestCaseRetryByListerner.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <skipped/>
  </testcase> <!-- Test2 -->
</testsuite> <!-- com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner -->
