<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RAM-PC" ignored="0" name="RetryMulitpleTestCases" tests="4" failures="1" timestamp="12 Mar 2020 09:02:58 GMT" time="0.126" errors="0">
  <testcase name="Test1" time="0.036" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner"/>
  <testcase name="Test2" time="0.011" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.retryListenerIAnnotationTransformer.TestCaseRetryByListerner.Test2(TestCaseRetryByListerner.java:17)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMulitpleTestCases -->
